In [279]:
import pandas as pd
import numpy as np
import re
from difflib import SequenceMatcher

In [305]:
data_location = 'output/1ra. D AFA 1992-93.csv'

data = pd.read_csv(data_location)
data.fillna(value='Quitar', inplace=True)
#pd.options.display.max_rows = None

data1=data.Goleadores1
data2=data.Goleadores2
data3=data1.append(data2)
data3=data3.replace(", ", " , ", regex=True)
data3=data3.replace(" y ", " , ", regex=True)
data3=data3.replace(" e ", " , ", regex=True)
data3+=' ,'
data3=data3.replace(" \(3p\)", "", regex=True)
data3=data3.replace(" \(2p\)", "", regex=True)
data3=data3.replace(" \(1p\)", "", regex=True)
data3=data3.replace(" \(p\)", "", regex=True)
data3=data3.replace("\(", "", regex=True)
data3=data3.replace("\)", "", regex=True)

pattern=r'([^,]*) (?:, ?)'
pattern2=r'([^\d]*)(\d?)'
lista=[]
jugadores=[]
goles=[]
for x in data3:
    gld=re.findall(pattern, x)
    if gld:
        for y in gld:
            lista.append(y)
for z in lista:
    gld2=re.findall(pattern2, z)
    if gld2:
        jugadores.append(gld2[0][0])
        goles.append(gld2[0][1])
        
Jugador = []
Goles = []
df=pd.DataFrame({"Jugador":Jugador,
                "Goles":Goles})
df['Jugador']=jugadores
df['Goles']=goles
df['Goles']=df['Goles'].replace ('', 1)
df['Jugador']=df['Jugador'].replace("\)", "", regex=True)
df['Goles']=df['Goles'].astype(int)

In [306]:
def unique_similars (df):
    uni_elements=[]
    uni_elements.append (df['Jugador'][0])
    
    for index, rep_jugador in enumerate (df['Jugador']):
        match= False
        for uni_element in uni_elements:
            if SequenceMatcher(None, rep_jugador, uni_element).ratio()>0.8:
                match = True
                df['Jugador'][index]=uni_element
        if match == False:
            uni_elements.append(rep_jugador)
    return df
df=unique_similars(df)

<ipython-input-306-a9926d49f374>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Jugador'][index]=uni_element

In [310]:
pd.options.display.max_rows = None
agrupados=df.groupby('Jugador')['Goles'].sum()
Goles2 = []
df2=pd.DataFrame({"Goles2":agrupados})
df2=df2.sort_values(['Goles2'], ascending=False)
df2.head(12)

                        Goles2
Jugador
Quitar                     137
Marcelo N. Luchetti         23
Juan de D. Quiroga          23
Rubén O. Moraglio           22
Hernán G. Izquierdo         13
Norberto U. Humberto        12
Gustavo G. Medina           12
Gustavo A. Martínez         12
Jorge O. Torres             12
Marcelo R. Salvatierra      12
Jorge R. Ramayo             11
Héctor A. Martín            11